name = "Modrinth SMP"
author = "Modrinth SMP"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8879d133901cd6179130ac0e69654a5a8e985c862290ccfaac18cff733cef229"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"

[options]
acceptable-game-versions = ["1.19.2"]
