name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac653308ac9ee37f8a9452632c3654cc899ab8d58356a610f0d38b6b51e093c"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
