name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "628bf5ffc3668e9f4b289c7df293f65b03d986ba31cafc5e417b1f62a3285b4b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
