name = "Modrinth SMP"
author = "Modrinth SMP"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30b7d519f3bfd7b01496180321b2e02ae000ea062336ef97e092369ba901373a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.27"

[options]
acceptable-game-versions = ["1.19.2"]
