name = "Modrinth SMP"
author = "Modrinth SMP"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e98dc786feb0cc3a3c1fb444f70133f45d6d1b4b786565e7a6970a6bae4bbfc"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"

[options]
acceptable-game-versions = ["1.19.2"]
