name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0dd684a354a99ac532f15b92407a892b4cc831ad181042ee8909c3a78be4619"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
