name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b20423665dfead5f7273088ade1a3d229cf810df0a7abe819b2e8a488ca9148"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
