name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "660587e488b53727683f133355a9cf86468ee26a2901a983fb405a8dee10fa66"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
