name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8e7b7acfd9c8f505894432af21f0e2e946afeb576811d72fc4adfd3f5c1f2ab"

[versions]
minecraft = "1.18.2"
quilt = "0.18.1-beta.12"

[options]
acceptable-game-versions = ["1.18.2"]
