name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92e17588559f6423727408cc0e7b040582da5606f03c7712530af5c603272bf1"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
