name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4014b88b06915773567d55b771c0d45cec9075dd69d54536265020f2ff3f644e"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
