name = "Modrinth SMP"
author = "Modrinth SMP"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e06865ba997dd5eed30bfc605c576dc82204c9fd1478f57347377cf83d5f0586"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.27"

[options]
acceptable-game-versions = ["1.19.2"]
