name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de562d96b91f6a4490036dfc61c28b7aa44bbec0a2a65dcef57485cea4dc9b8"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
