name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e0b06aaebf99c35173bab0b9d54fca5d8407557e75907e2b99c8458da680dcd"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
