name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d97a94bf0f5e9a7a3351c4247327f0bbf76643e28ca3f776d59010640121a20b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
