name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca56f08f79417513dbd8bcf6d707ec3b40eaa585477d241ef1dc58936858bdba"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
