name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6afe0dec902295d624d869b91f93bdb73ede79c240ce96583500282c80ceb86d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
