name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "535f52b9cbf0498ac026f2a8bf913a01ee53acd8840240b6d363741921287f14"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
