name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0085d94887716d5dc5963756a8bab1c697009a020a2f02e7ec8d2e6eeeaa06a2"

[versions]
minecraft = "1.18.2"
quilt = "0.18.1-beta.12"

[options]
acceptable-game-versions = ["1.18.2"]
