name = "Modrinth SMP"
author = "Modrinth SMP"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42f60889b428143739d5c4063aa7d1e74eaea9d07c7df166ae69268b4fe6e823"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"

[options]
acceptable-game-versions = ["1.19.2"]
