name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2abd385ad10e8f7c03e1d809d7ba9e5c6acb73c7945845613e6d6b667e41c33d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
