name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af5d2a77a3d9188dda6ac98015f336d5bf60dfa2c4367c7ceb3e9cc4670d9734"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
