name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "221c3bd4798857f77b8af8f2c63fd479e31efdac10e847a80d8e3c090149f4d8"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
