name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5533f3736cf882cf8356a3908c00074258489ecaa1bd83303bdee854d1b9a5bd"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
