name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caa15b1157b41ae54398294329d792b147c17cefb7b5ac6711e0fb670b99976f"

[versions]
minecraft = "1.18.2"
quilt = "0.18.1-beta.12"

[options]
acceptable-game-versions = ["1.18.2"]
