name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8aa3438620e5ea1735a64fabd1be7d9b808e6874205f486606b94777c1c3afc"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
