name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c90177eb6da91cb55d64f25fe769a1693533699c324efbec7a9c69b586dff307"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
