name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "839cf38e718c102c457ca21fa47b322dff35604919e4fcccdf2c57babe0b005d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
