name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "225bb16f50e40be3f15afe2e53ce04f1b18998498956a05658d33257ba1ed0fa"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
