name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c049c15198c35b6c2386c20beacfb67bf05d5fcf6aa0576bcd35ff17b12c357a"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
