name = "Modrinth SMP"
author = "Modrinth SMP"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a33df08b9ac790dd0931a31a4a0e486029b33d83f30b4f0ab55c88ba90342cff"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.27"

[options]
acceptable-game-versions = ["1.19.2"]
