name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25b1eade7af2bfa1f56d680333d7042c6bb1410c68b901fcb77af7c68efa93b2"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
