name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6ea4eb2ef85d14d785c767402a704031d310fcabc0c6fdb0888527a446482b5"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
