name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b52dbbc8dbf4bf903b37e33e399252ee66fb308ff78034c7493035fceea103e1"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6"
