name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ea77d8fc9c482c9e82bb0c5814931286b69e2db2fe974f77022a0530574b59"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
