name = "Modrinth SMP"
author = "Modrinth SMP"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f960cd365b2df60593dbd22b9dde2254557ba89c0a1571360a160fde95f24bf"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"

[options]
acceptable-game-versions = ["1.19.2"]
