name = "Modrinth SMP"
author = "Modrinth SMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "575e262c027a6f4465dd14bf3bd180edbe886e6993de6115fed754de1e37886b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.6-beta.2"
