name = "Geckolib"
filename = "geckolib-fabric-1.18-3.0.75.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/8BmcQJ2H/versions/V1WV1xOD/geckolib-fabric-1.18-3.0.75.jar"
hash-format = "sha1"
hash = "1b2ed01288d485048de2fbde31314aed94a603c3"

[update]
[update.modrinth]
mod-id = "8BmcQJ2H"
version = "V1WV1xOD"
