name = "Simple Voice Chat"
filename = "voicechat-quilt-1.18.2-2.3.12.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/DCgHdBA4/voicechat-quilt-1.18.2-2.3.12.jar"
hash-format = "sha1"
hash = "604259a1381d1adefc1edca957a4d5d396695bbd"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "DCgHdBA4"

[option]
optional = true
default = true
