name = "Simple Voice Chat"
filename = "voicechat-quilt-1.19.2-2.3.15.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/u3pVBlpU/voicechat-quilt-1.19.2-2.3.15.jar"
hash-format = "sha1"
hash = "7e0097c2c665fa2a7fb9fe2184cb1ad51418439a"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "u3pVBlpU"

[option]
optional = true
description = "Most players on the server communicate with this mod, so it is recommended that you remove this only for compatibility reasons. Know that this is needed to hear other people and interact with groups."
default = true
