name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.2-2.3.12.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/ClJ8ePwh/voicechat-fabric-1.18.2-2.3.12.jar"
hash-format = "sha1"
hash = "1e81696490b306f2e26134ba0bea4c486153cedd"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "ClJ8ePwh"

[option]
optional = true
default = true
