name = "Solid Mobs"
filename = "solid_mobs-1.5-mc1.18.x.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/uEXYxtEF/versions/1.5.mc1.18.x/solid_mobs-1.5-mc1.18.x.jar"
hash-format = "sha1"
hash = "baa5be554ea34198914b5536387dd14e515a6f27"

[update]
[update.modrinth]
mod-id = "uEXYxtEF"
version = "cQQIhT78"
