name: publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Packwiz
        run: |
          wget https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          7z x Linux\ 64-bit\ x86.zip
          chmod +x packwiz
      - name: Build mrpack
        run: ./packwiz modrinth export
      - name: Set outputs
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Rename file
        run: mv *.mrpack 'Modrinth SMP-${SHORT_SHA}.mrpack'
      - name: Publish mrpack
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: PEMTFQFO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: '*.mrpack'
          version: ${SHORT_SHA}
          loaders: quilt
          game-versions: '1.18.2'
