[gate-of-babylon]
name = "Gate of Babylon"
url = "https://www.curseforge.com/minecraft/mc-mods/gate-of-babylon"

["spellbound-1.9.1"]
name = "Spellbound"
url = "https://github.com/Tigereye504/spellbound"
